#!/usr/bin/env node
'use strict';
// Deploy this repo to an Alexa-hosted skill without clobbering the things that
// belong to the skill rather than to the repo.
//
//   node scripts/deploy.js <skillId>
//   npm run deploy -- <skillId>
//
// Three fields are per-skill and must survive a deploy:
//
//   manifest.publishingInformation...name    "Audiobookshelf (dev)" vs "Audiobookshelf"
//   languageModel.invocationName             what you actually say to Alexa
//   apis.custom.endpoint (and .regions)      generated by Amazon at skill creation
//
// The endpoint is the dangerous one. Amazon fills it in once, and the developer
// console uses it to decide whether a skill's code is Alexa-hosted. Pushing a
// manifest without it makes the console report "Your default endpoint has
// changed and the code below is no longer hosted by Alexa" -- the code is fine,
// but the console loses its link to it.
//
// So this reads the live manifest and model, overwrites only what the repo
// owns, and leaves the rest exactly as deployed.

const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const skillId = process.argv[2];
if (!skillId) {
  console.error('usage: node scripts/deploy.js <skillId>');
  process.exit(1);
}

const ask = (...args) => execFileSync('ask', args, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
const askJson = (...args) => JSON.parse(ask(...args));
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'abs-deploy-'));
const write = (name, obj) => {
  const p = path.join(tmp, name);
  fs.writeFileSync(p, JSON.stringify(obj, null, 2));
  return p;
};

function deployManifest() {
  const live = askJson('smapi', 'get-skill-manifest', '-s', skillId, '-g', 'development').manifest;
  const repo = JSON.parse(fs.readFileSync(path.join(ROOT, 'skill-package', 'skill.json'), 'utf8')).manifest;

  const liveLocale = live.publishingInformation.locales['en-US'] || {};
  const repoLocale = repo.publishingInformation.locales['en-US'] || {};

  const merged = JSON.parse(JSON.stringify(live));
  // repo owns the copy...
  for (const k of ['summary', 'description', 'keywords', 'examplePhrases']) {
    if (repoLocale[k] !== undefined) merged.publishingInformation.locales['en-US'][k] = repoLocale[k];
  }
  if (repo.publishingInformation.testingInstructions !== undefined) {
    merged.publishingInformation.testingInstructions = repo.publishingInformation.testingInstructions;
  }
  if (repo.apis && repo.apis.custom && repo.apis.custom.interfaces) {
    merged.apis.custom.interfaces = repo.apis.custom.interfaces;
  }
  // ...the skill keeps its own name and endpoint
  merged.publishingInformation.locales['en-US'].name = liveLocale.name;

  ask('smapi', 'update-skill-manifest', '-s', skillId, '-g', 'development',
      '--manifest', 'file:' + write('manifest.json', { manifest: merged }));
  console.log('  manifest  updated (kept name %j and the hosted endpoint)', liveLocale.name);
}

function deployModel() {
  const live = askJson('smapi', 'get-interaction-model', '-s', skillId, '-g', 'development', '-l', 'en-US');
  const repo = JSON.parse(fs.readFileSync(
    path.join(ROOT, 'skill-package', 'interactionModels', 'custom', 'en-US.json'), 'utf8'));

  const merged = JSON.parse(JSON.stringify(repo));
  // the invocation name is how a device reaches this specific skill
  merged.interactionModel.languageModel.invocationName =
    live.interactionModel.languageModel.invocationName;

  ask('smapi', 'set-interaction-model', '-s', skillId, '-g', 'development', '-l', 'en-US',
      '--interaction-model', 'file:' + write('model.json', merged));
  console.log('  model     updated (kept invocation name %j)',
    live.interactionModel.languageModel.invocationName);
}

function deployCode() {
  const meta = askJson('smapi', 'get-alexa-hosted-skill-metadata', '-s', skillId);
  const repoUrl = meta.alexaHosted.repository.url;
  const creds = askJson('smapi', 'generate-credentials-for-alexa-hosted-skill',
    '-s', skillId, '--repository-url', repoUrl, '--repository-type', 'GIT').repositoryCredentials;
  const auth = repoUrl.replace('https://',
    `https://${encodeURIComponent(creds.username)}:${encodeURIComponent(creds.password)}@`);

  const clone = path.join(tmp, 'hosted');
  execFileSync('git', ['clone', '--quiet', auth, clone], { stdio: ['ignore', 'ignore', 'inherit'] });

  // Copy code only. config.js lives in the hosted repo because Alexa-hosted has
  // no environment-variable configuration, and it must not be overwritten.
  const src = path.join(ROOT, 'lambda');
  const dst = path.join(clone, 'lambda');
  fs.mkdirSync(path.join(dst, 'lib'), { recursive: true });
  for (const f of ['index.js', 'package.json', 'package-lock.json', 'config.example.js']) {
    fs.copyFileSync(path.join(src, f), path.join(dst, f));
  }
  for (const f of fs.readdirSync(path.join(src, 'lib'))) {
    fs.copyFileSync(path.join(src, 'lib', f), path.join(dst, 'lib', f));
  }

  const status = execFileSync('git', ['status', '--porcelain'], { cwd: clone, encoding: 'utf8' });
  if (!status.trim()) { console.log('  code      already up to date'); return; }

  const sha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim();
  execFileSync('git', ['add', '-A'], { cwd: clone });
  execFileSync('git', ['-c', 'user.email=deploy@localhost', '-c', 'user.name=deploy',
    'commit', '-q', '-m', `Deploy ${sha}`], { cwd: clone });
  execFileSync('git', ['push', auth, 'master'], { cwd: clone, stdio: ['ignore', 'ignore', 'pipe'] });
  console.log('  code      pushed (from repo %s)', sha);
}

console.log('deploying to %s', skillId);
deployCode();
deployManifest();
deployModel();
fs.rmSync(tmp, { recursive: true, force: true });
console.log('\ncheck progress with:\n  ask smapi get-skill-status -s %s', skillId);
